NumPy

NumPy is a module that aims to make calculations in Python lighter.

In [1]:
# Import NumPy

import numpy as np

In [2]:
# Checking NumPy Version

print(np.__version__)

1.24.3


In [3]:
# creating a NumPy array

arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


Task 1 (import numpy, checking version, bikin contoh numpy, type data)

In [5]:
# Import NumPy

import numpy as np

In [6]:
# Checking NumPy Version

print(np.__version__)

1.24.3


In [7]:
# creating a NumPy array

strings = np.array(["Kami", "adalah", "Kelompok 5"])
print(strings)

['Kami' 'adalah' 'Kelompok 5']


In [8]:
import numpy as np

strings = np.array(["Kami", "adalah", "Kelompok 5"])

print(strings)

print(type(strings))

['Kami' 'adalah' 'Kelompok 5']
<class 'numpy.ndarray'>


In [11]:
# Use a tuple to create a Numpy array

import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


Dimensions in Arrays

A dimension in arrays is one level of array depth (nested arrays).

In [12]:
# 0-D

In [13]:
import numpy as np

arr = np.array(42)

print(arr)

42


In [14]:
# Create a 1-D array

In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [16]:
# Create a 2-D array containing two arrays

In [17]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Task 2 (buat 0, 1, 2 dimesion)

In [19]:
# 0-D

import numpy as np

arr = np.array(1.5)

print(arr)

1.5


In [20]:
# 1-D

import numpy as np

arr = np.array(["Data Analyst", "MyEduSolve"])

print(arr)

['Data Analyst' 'MyEduSolve']


In [21]:
# 2-D

import numpy as np

arr = np.array([["Kelompok 1"], ["Kelompok 2"], ["Kelompok 3"], ["Kelompok 4"], ["Kelompok 5"]])

print(arr)

[['Kelompok 1']
 ['Kelompok 2']
 ['Kelompok 3']
 ['Kelompok 4']
 ['Kelompok 5']]


In [22]:
# Create a 3-D array with two 2-D arrays, both containing two arrays

In [27]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [28]:
# Check how many dimensions the arrays have

In [30]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
# Create an array with 5 dimensions and verify that it has 5 dimensions

In [39]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5], ndmin=5)

print(arr)
print('number of dimension :', arr.ndim)

[[[[[1 2 3 4 5]]]]]
number of dimension : 5


Task 3 (bikin bbrp array, cek ndim, bikin sebuah array ndim)

In [34]:
import numpy as np

o = np.array(1.1)
p = np.array([1.2, 1.3, 1.4, 1.5, 1.6])
q = np.array([[1.2, 1.3, 1.4], [1.4, 1.5, 1.6], [1.7, 1.8, 1.9]])
r = np.array([[[1.2, 1.3, 1.4], [1.5, 1.6, 1.7]], [[1.8, 1.9, 1.10], [1.11, 1.12, 1.13]]])

print(o.ndim)
print(p.ndim)
print(q.ndim)
print(r.ndim)

0
1
2
3


In [38]:
import numpy as np

arr = np.array([1.2, 1.3, 1.4, 1.5, 1.6], ndmin=5)

print(arr)
print('number of dimension :', arr.ndim)

[[[[[1.2 1.3 1.4 1.5 1.6]]]]]
number of dimension : 5


In [ ]:
# Get the second element from the following array

In [46]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[1])

2


In [47]:
# Get the third and fourth elements from the followning array and add then

In [49]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [50]:
# Access the element on the first row, second column

In [51]:
import numpy as np

arr= np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1 st row: ', arr[0, 1])

2nd element on 1 st row:  2


In [52]:
# Access the element on the 2nd, 5th column

In [53]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[1,4])

10


In [54]:
# Access the third element of the second array of the first array

In [55]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[1, 0, 2])

9


Task 4 (bikin array 2D, isi nya ada min 3 list, panggil (operasi math), slicing)

In [57]:
import numpy as np

arr= np.array([[1.1, 2.2, 3.3, 4.4, 5.5], [6.1, 7.1, 8.1, 9.1, 10.1], [11.4 , 12.4, 13.4, 14.4, 15.4]])

print('2nd element on 2 nd row: ', arr[0, 1])

2nd element on 2 nd row:  2.2


In [58]:
import numpy as np

arr= np.array([[1.1, 2.2, 3.3, 4.4, 5.5], [6.1, 7.1, 8.1, 9.1, 10.1], [11.4 , 12.4, 13.4, 14.4, 15.4]])

print('2nd element on 2 nd row: ', arr[1, 1])

2nd element on 2 nd row:  7.1


In [59]:
import numpy as np

arr= np.array([[1.1, 2.2, 3.3, 4.4, 5.5], [6.1, 7.1, 8.1, 9.1, 10.1], [11.4 , 12.4, 13.4, 14.4, 15.4]])

print('2nd element on 2 nd row: ', arr[2, 1])

2nd element on 2 nd row:  12.4
